server:
  port: 80
spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
#  mvc:
#    static-path-pattern: /**
#  web:
#    resources:
#      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

# 七牛云配置
qiniu:
  accessKey: CazQQRyp5MiLDR_LiBruYeG7xyShydm_rLArdTJb
  secretKey: oOlv82H51dZ-rb11H4VOBoQ4Vo9M7kgauE02WqfX
  bucket: picgoimgs
  domain: http://cdn.zyboy.site/

